---

- name: Ensures go-agent configuration
  become: yes
  template:
    src: defaults.j2
    dest: /etc/default/go-agent
    owner: "{{ gocd_agent.user }}"
    group: "{{ gocd_agent.user }}"
  notify:
    - restart go-agent

- name: Configure Git for Go CD user
  become: yes
  become_user: "{{ gocd_agent.user }}"
  template:
    src: gitconfig.j2
    dest: /home/{{ gocd_agent.user }}/.gitconfig

- name: Create defaults file for agent
  become: yes
  template:
    src: defaults.j2
    dest: /etc/default/go-agent

- name: Ensure the agent is started
  become: yes
  service:
    name: "go-agent"
    state: started
